version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - ecommerce-network
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true

networks:
  ecommerce-network:
    external: true
